# SwiftLint configuration for md2cb

# Rules to disable
disabled_rules:
  - trailing_comma  # Allow trailing commas

# Rules to opt-in
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - redundant_type_annotation
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces

# Line length
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

# Identifier name rules
identifier_name:
  min_length:
    warning: 1
  excluded:
    - i
    - j
    - x
    - y
    - id

# Function body length
function_body_length:
  warning: 60
  error: 100

# Type body length
type_body_length:
  warning: 400
  error: 500

# Nesting
nesting:
  type_level: 2
  function_level: 3

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# File length
file_length:
  warning: 600
  error: 1000

# Excluded paths
excluded:
  - .build
  - Package.swift
